### PR TITLE
Create map page on Sandbox

### LINKED ISSUE #2: HTML for the maps section
As @furilo pointed out, this needs to be done:

- html in sandbox with the map design
- put a placeholder carto map, and the controls (tree in the sidebar)
- create the local navigation we have for the gencat project
- go with the styles (colors) from the main fork, in a next to-do we will "localize" colors to the new layout

### PR DESCRIPTION
**Pull request by martgnz**
- Follows the Sketch layout
- Sample map

Fixes #2

### CODE REVIEW

**Comment by martgnz** [comment]
We should probably fix the "Compare" button. At the moment is on the right, aligned with the breadcrumbs (but we are not painting them in this page).

I recommend changing the header in this page to have the title and the button in the same row, although @furilo knows more about it

**Comment by furilo** [comment]
- I'd remove the "Compare" button
- Which were the options for the 5 top buttons? I wonder if we are going to show the menu overlay only for the first option, or for everyone.

**Comment by martgnz** [comment]
- Gasto por habitante
- Ingresos por habitante
- N de habitantes
- Servicios públicos por habitante
- Deuda por habitante

**Comment by ferblape** [comment]
🚀

**Pull request merged**
